/* Paratuberculose GDS 32-65 v1.0.0 — local-first PWA */
const APP_VERSION='1.0.0';
const DB_NAME='ptb_gds_32_65';
const DB_VERSION=1;
const STORES=['herds','campaigns','nonnegatives','descendants','introductions','animals','analysisLots','analysisTreatments','meta'];
const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const digits=s=>String(s??'').replace(/\D/g,'');
const today=()=>new Date().toISOString().slice(0,10);
const fmtDate=v=>{if(!v)return''; const d=v instanceof Date?v:new Date(v); return isNaN(d)?String(v):d.toLocaleDateString('fr-FR')};
const num=v=>Number(String(v??'').replace(',','.'))||0;
const key=(...p)=>p.map(x=>String(x??'')).join('|');
function campaignFromDate(v){const d=v instanceof Date?v:new Date(v); if(isNaN(d))return''; const y=d.getFullYear(); return d.getMonth()>=6?`${y}/${y+1}`:`${y-1}/${y}`}
function currentCampaignDefault(){return campaignFromDate(new Date())}
function toast(msg){const t=$('#toast');t.textContent=msg;t.hidden=false;clearTimeout(toast._t);toast._t=setTimeout(()=>t.hidden=true,3200)}
function download(name,content,type='text/plain;charset=utf-8'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500)}
function csvEscape(v){const s=String(v??''); return /[;"\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s}
function toCSV(rows,headers){return [headers.join(';'),...rows.map(r=>headers.map(h=>csvEscape(r[h])).join(';'))].join('\n')}

class IDBStore{
  constructor(){this.db=null}
  open(){return new Promise((res,rej)=>{const rq=indexedDB.open(DB_NAME,DB_VERSION);rq.onupgradeneeded=()=>{const db=rq.result;for(const s of STORES)if(!db.objectStoreNames.contains(s))db.createObjectStore(s,{keyPath:'id'})};rq.onsuccess=()=>{this.db=rq.result;res(this)};rq.onerror=()=>rej(rq.error)})}
  tx(store,mode='readonly'){return this.db.transaction(store,mode).objectStore(store)}
  all(store){return new Promise((res,rej)=>{const rq=this.tx(store).getAll();rq.onsuccess=()=>res(rq.result);rq.onerror=()=>rej(rq.error)})}
  get(store,id){return new Promise((res,rej)=>{const rq=this.tx(store).get(id);rq.onsuccess=()=>res(rq.result);rq.onerror=()=>rej(rq.error)})}
  put(store,obj){return new Promise((res,rej)=>{const rq=this.tx(store,'readwrite').put(obj);rq.onsuccess=()=>res(obj);rq.onerror=()=>rej(rq.error)})}
  bulkPut(store,arr){return new Promise((res,rej)=>{const tx=this.db.transaction(store,'readwrite'),os=tx.objectStore(store);arr.forEach(o=>os.put(o));tx.oncomplete=()=>res(arr.length);tx.onerror=()=>rej(tx.error)})}
  clear(store){return new Promise((res,rej)=>{const rq=this.tx(store,'readwrite').clear();rq.onsuccess=()=>res();rq.onerror=()=>rej(rq.error)})}
  delete(store,id){return new Promise((res,rej)=>{const rq=this.tx(store,'readwrite').delete(id);rq.onsuccess=()=>res();rq.onerror=()=>rej(rq.error)})}
}
const db=new IDBStore();
const state={view:'dashboard',campaign:'',herds:[],campaigns:[],nonnegatives:[],descendants:[],introductions:[],animals:[],analysisLots:[],analysisTreatments:[],meta:{},herdFilters:{q:'',dept:'',mode:''}};

async function loadState(){
  for(const s of ['herds','campaigns','nonnegatives','descendants','introductions','animals','analysisLots','analysisTreatments']) state[s]=await db.all(s);
  const meta=await db.all('meta'); state.meta=Object.fromEntries(meta.map(x=>[x.id,x.value]));
  state.campaign=state.meta.currentCampaign||currentCampaignDefault();
  if(!state.meta.currentCampaign)await setMeta('currentCampaign',state.campaign);
}
async function setMeta(id,value){state.meta[id]=value;await db.put('meta',{id,value})}

function getCampaignsList(){const set=new Set(state.campaigns.map(x=>x.campaign).filter(Boolean));set.add(state.campaign); return [...set].sort((a,b)=>b.localeCompare(a))}
function populateCampaignSelector(){const s=$('#globalCampaign');if(!s)return;s.innerHTML=getCampaignsList().map(c=>`<option ${c===state.campaign?'selected':''}>${esc(c)}</option>`).join('');}
function analysisAggregate(campaign=state.campaign){
  const map=new Map();
  for(const lot of state.analysisLots.filter(x=>x.campaign===campaign)){
    const k=String(lot.ede); if(!map.has(k))map.set(k,{ede:k,dept:lot.dept,campaign,lots:0,first:null,last:null,tested:0,positive:0,lastUpdate:null,dossiers:[]});
    const a=map.get(k);a.lots++; const d=lot.sampleDate?new Date(lot.sampleDate):null;if(d&&!isNaN(d)){if(!a.first||d<a.first)a.first=d;if(!a.last||d>a.last)a.last=d}
    a.tested+=num(lot.tested);a.positive+=num(lot.positive); const u=lot.lastUpdate?new Date(lot.lastUpdate):null;if(u&&!isNaN(u)&&(!a.lastUpdate||u>a.lastUpdate))a.lastUpdate=u;if(lot.labFile)a.dossiers.push(lot.labFile);
  }
  for(const a of map.values()){a.negative=Math.max(0,a.tested-a.positive);const t=state.analysisTreatments.find(x=>x.id===key(a.ede,campaign));const td=t?.treatmentDate?new Date(t.treatmentDate):null;const current=td&&a.lastUpdate&&td>=a.lastUpdate&&t.qualificationUpdated&&(a.positive===0||t.positivesManaged);a.status=current?'TRAITÉ':a.positive>0?'POSITIF À TRAITER':'À TRAITER';a.treatment=t||null}
  return map;
}
function animalIndex(){const m=new Map();for(const a of state.animals)m.set(String(a.animalId),a);return m}
function herdByEde(ede){return state.herds.find(h=>String(h.ede)===String(ede))}
function historyFor(ede){return state.campaigns.filter(c=>String(c.ede)===String(ede)).sort((a,b)=>String(b.campaign).localeCompare(String(a.campaign)))}
function activeAnimals(ede){return state.animals.filter(a=>String(a.ede)===String(ede))}

function render(){populateCampaignSelector(); $$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view)); const fn=views[state.view]||views.dashboard; $('#app').innerHTML=fn(); bindView()}
const pageHead=(title,sub='',actions='')=>`<div class="page-head"><div><h1>${title}</h1><p>${sub}</p></div><div class="actions">${actions}</div></div>`;
const badgeMode=m=>m?`<span class="badge ${norm(m).includes('garantie')?'garantie':'ass'}">${esc(m)}</span>`:'';

const views={
 dashboard(){
   const ag=analysisAggregate(); const vals=[...ag.values()]; const positives=vals.filter(x=>x.positive>0).length; const todo=vals.filter(x=>x.status!=='TRAITÉ').length;
   const presentNN=state.nonnegatives.filter(n=>{const a=animalIndex().get(String(n.animalId));return a?.presence==='Présent'||n.presence==='Présent'}).length;
   return pageHead('Tableau de bord',`Campagne ${esc(state.campaign)}`)+`<div class="grid kpi-grid">
    ${kpi('Cheptels engagés',state.herds.length,'32 + 65')}${kpi('Garantie',state.herds.filter(h=>norm(h.mode).includes('garantie')).length,'qualification favorable')}${kpi('Assainissement',state.herds.filter(h=>norm(h.mode).includes('assain')).length,'plan de maîtrise')}${kpi('Analyses importées',vals.length,`${todo} dossier(s) à traiter`)}
    ${kpi('Cheptels positifs',positives,'campagne active')}${kpi('Non négatifs présents',presentNN,'à surveiller')}${kpi('Descendants',state.descendants.length,'historique enregistré')}${kpi('Animaux chargés',state.animals.length,'imports 32 + 65')}
   </div><div class="split"><div class="card"><h2>À traiter</h2>${analysisTable(vals.filter(x=>x.status!=='TRAITÉ').slice(0,12))}</div><div class="card"><h2>Accès rapide</h2><div class="actions"><button class="primary" data-go="imports">Importer</button><button class="ghost" data-go="herds">Chercher un éleveur</button><button class="ghost" data-go="exports">Faire un export</button></div><div class="notice">L'application est locale d'abord : les données restent dans ce navigateur. Une synchronisation Supabase peut être configurée dans Paramètres.</div></div></div>`;
 },
 herds(){
   const f=state.herdFilters; const rows=filteredHerds();
   return pageHead('Éleveurs',`${rows.length} cheptel(s) affiché(s)`)+`<div class="toolbar"><input id="herdQ" type="search" placeholder="EDE, nom, commune, vétérinaire…" value="${esc(f.q)}"><select id="herdDept"><option value="">32 + 65</option><option ${f.dept==='32'?'selected':''}>32</option><option ${f.dept==='65'?'selected':''}>65</option></select><select id="herdMode"><option value="">Garantie + Assainissement</option><option ${f.mode==='Garantie'?'selected':''}>Garantie</option><option ${f.mode==='Assainissement'?'selected':''}>Assainissement</option></select></div>${herdTable(rows)}`;
 },
 campaigns(){
   const rows=state.campaigns.filter(c=>c.campaign===state.campaign); const ag=analysisAggregate();
   const merged=rows.map(c=>({...c,analysis:ag.get(String(c.ede))}));
   return pageHead('Campagnes',`Suivi ${esc(state.campaign)}`)+`<div class="card"><div class="stat-line"><span class="stat-pill">${rows.length} cheptels</span><span class="stat-pill">${[...ag.values()].reduce((s,x)=>s+x.tested,0)} prélèvements</span><span class="stat-pill">${[...ag.values()].reduce((s,x)=>s+x.positive,0)} positifs</span></div></div><div class="table-wrap"><table><thead><tr><th>EDE</th><th>Éleveur</th><th>Mode</th><th>Dépistage prévu</th><th>Dépistés</th><th>Négatifs</th><th>Positifs</th><th>Date</th><th>Statut analyse</th><th>Qualification campagne</th></tr></thead><tbody>${merged.map(c=>{const h=herdByEde(c.ede),a=c.analysis;return`<tr class="click-row" data-herd="${esc(c.ede)}"><td>${esc(c.ede)}</td><td>${esc(h?.name||c.name||'')}</td><td>${badgeMode(h?.mode||c.mode)}</td><td>${esc(c.screeningPlanned||'')}</td><td>${a?a.tested:esc(c.tested||'')}</td><td>${a?a.negative:esc(c.negative||'')}</td><td>${a?a.positive:esc(c.positive||'')}</td><td>${a?fmtDate(a.last):fmtDate(c.campaignDate)}</td><td>${a?statusBadge(a.status):''}</td><td>${esc(c.status||'')}</td></tr>`}).join('')}</tbody></table></div>`;
 },
 analysis(){const vals=[...analysisAggregate().values()].sort((a,b)=>(a.status==='POSITIF À TRAITER'?-2:a.status==='À TRAITER'?-1:1)-(b.status==='POSITIF À TRAITER'?-2:b.status==='À TRAITER'?-1:1));return pageHead('Analyses',`Imports agrégés pour ${esc(state.campaign)}`,`<button class="primary" data-go="imports">Importer analyses</button>`)+analysisTable(vals)},
 animals(){return pageHead('Animaux',`${state.animals.length} bovin(s) chargé(s)`,`<button class="primary" data-go="imports">Actualiser les animaux</button>`)+`<div class="toolbar"><input id="animalQ" type="search" placeholder="ID bovin, n° travail, nom, EDE…"></div><div id="animalResults">${animalTable(state.animals.slice(0,200))}</div>`},
 nonneg(){const ai=animalIndex();return pageHead('Non négatifs',`${state.nonnegatives.length} enregistrement(s)`,`<button class="primary" id="btnAddNN">+ Ajouter</button>`)+`<div class="table-wrap"><table><thead><tr><th>Campagne</th><th>EDE</th><th>Animal</th><th>Nom / travail</th><th>Résultat</th><th>Date</th><th>Présence</th><th>Sortie</th></tr></thead><tbody>${state.nonnegatives.map(n=>{const a=ai.get(String(n.animalId));return`<tr class="click-row" data-herd="${esc(n.ede)}"><td>${esc(n.campaign||'')}</td><td>${esc(n.ede)}</td><td>${esc(n.animalId)}</td><td>${esc(a?.name||n.name||'')} ${a?.workNo?`(${esc(a.workNo)})`:''}</td><td>${esc(n.result||'')}</td><td>${fmtDate(n.date)}</td><td>${esc(a?.presence||n.presence||'')}</td><td>${fmtDate(a?.exitDate||n.exitDate)}</td></tr>`}).join('')}</tbody></table></div>`},
 introductions(){return pageHead('Introductions',`${state.introductions.length} enregistrement(s)`)+simpleObjectTable(state.introductions,['dept','ede','animalId','entryDate','origin','control','result','comment'])},
 exports(){return pageHead('Exports & bilan','Listes opérationnelles et bilan annuel')+`<div class="grid split"><div class="card"><h2>Listes d'élevages</h2><div class="actions"><button class="primary export-btn" data-export="engages">Engagés 32-65</button><button class="ghost export-btn" data-export="garantie">Garantie</button><button class="ghost export-btn" data-export="ass">Assainissement</button><button class="ghost export-btn" data-export="garantie32">Garantie 32</button><button class="ghost export-btn" data-export="garantie65">Garantie 65</button><button class="ghost export-btn" data-export="ass32">Assainissement 32</button><button class="ghost export-btn" data-export="ass65">Assainissement 65</button></div></div><div class="card"><h2>Bilan ${esc(state.campaign)}</h2>${balanceHTML()}<button class="primary export-btn" data-export="bilan">Exporter le bilan CSV</button></div></div><div class="card"><h2>Exports de suivi</h2><div class="actions"><button class="ghost export-btn" data-export="positifs">Cheptels positifs</button><button class="ghost export-btn" data-export="nonnegpresent">Non négatifs présents</button><button class="ghost export-btn" data-export="descendants">Descendants</button><button class="ghost export-btn" data-export="introductions">Introductions</button></div></div>`},
 imports(){return pageHead('Imports','Tous les imports sont conservés dans la base locale',`<button class="primary" id="btnImportBundled">Charger l’historique fourni</button>`)+`<div class="grid split"><div>${importCard('migration','Migration initiale Excel','Importer le classeur historique V9.1 : CHEPTELS, CAMPAGNES, NON_NEGATIFS, DESCENDANTS, INTRODUCTIONS','.xlsx,.xls')}${importCard('animals32','Animaux 32','Export bovins brut du 32, tel qu’il sort du logiciel métier.','.csv')}${importCard('animals65','Animaux 65','Export bovins brut du 65, tel qu’il sort du logiciel métier.','.csv')}</div><div>${importCard('analysis32','Analyses 32','Export analyses exploitation détaillé du 32.','.csv')}${importCard('analysis65','Analyses 65','Export analyses exploitation détaillé du 65.','.csv')}<div class="card"><h3>Principe</h3><p class="help">Les animaux remplacent l'état courant du département importé. Les analyses sont ajoutées par campagne et agrégées automatiquement par EDE, même si un cheptel a plusieurs lots. Les numéros individuels des non négatifs restent saisis manuellement.</p></div></div></div>`},
 settings(){return pageHead('Paramètres','Campagne active, sauvegardes et synchronisation')+`<div class="card"><h2>Campagne active</h2><div class="form-grid"><div class="field"><label>Campagne</label><input id="settingCampaign" value="${esc(state.campaign)}" placeholder="2026/2027"></div><div class="field"><label>&nbsp;</label><button class="primary" id="saveCampaign">Enregistrer</button></div></div></div><div class="card"><h2>Supabase (optionnel)</h2><p class="help">Le logiciel fonctionne déjà sans Supabase. Pour partager les données entre plusieurs postes, renseigner l'URL et la clé publique, puis utiliser la table générique fournie dans <code>supabase.sql</code>.</p><div class="form-grid"><div class="field"><label>URL Supabase</label><input id="sbUrl" value="${esc(state.meta.supabaseUrl||'')}"></div><div class="field"><label>Clé publique / anon</label><input id="sbKey" type="password" value="${esc(state.meta.supabaseKey||'')}"></div></div><div class="actions" style="margin-top:12px"><button class="primary" id="saveSupabase">Enregistrer</button><button class="ghost" id="pushSupabase">Envoyer vers Supabase</button><button class="ghost" id="pullSupabase">Récupérer Supabase</button></div></div><div class="card"><h2>Maintenance</h2><div class="actions"><button class="ghost" id="restoreJsonBtn">Restaurer JSON</button><input id="restoreJsonInput" type="file" accept="application/json" hidden><button class="danger" id="resetDbBtn">Réinitialiser la base locale</button></div></div>`}
};
function kpi(label,value,sub=''){return`<div class="kpi"><div class="label">${esc(label)}</div><div class="value">${esc(value)}</div><div class="sub">${esc(sub)}</div></div>`}
function statusBadge(s){return`<span class="badge ${s==='POSITIF À TRAITER'?'red':s==='À TRAITER'?'yellow':'green'}">${esc(s)}</span>`}
function analysisTable(rows){if(!rows.length)return'<div class="empty">Aucune analyse pour cette campagne.</div>';return`<div class="table-wrap"><table><thead><tr><th>EDE</th><th>Éleveur</th><th>Lots</th><th>Prélèvement</th><th>Dépistés</th><th>Négatifs</th><th>Positifs</th><th>Dernière MAJ</th><th>Statut</th><th></th></tr></thead><tbody>${rows.map(a=>`<tr><td>${esc(a.ede)}</td><td class="click-row" data-herd="${esc(a.ede)}">${esc(herdByEde(a.ede)?.name||'')}</td><td>${a.lots}</td><td>${fmtDate(a.last)}</td><td>${a.tested}</td><td>${a.negative}</td><td><strong>${a.positive}</strong></td><td>${fmtDate(a.lastUpdate)}</td><td>${statusBadge(a.status)}</td><td><button class="ghost analysis-treat" data-ede="${esc(a.ede)}">Traiter</button></td></tr>`).join('')}</tbody></table></div>`}
function filteredHerds(){const f=state.herdFilters;return state.herds.filter(h=>{const hay=norm([h.ede,h.name,h.commune,h.vet,h.mode,h.currentQualification].join(' '));return(!f.q||hay.includes(norm(f.q)))&&(!f.dept||String(h.dept)===f.dept)&&(!f.mode||norm(h.mode).includes(norm(f.mode)))})}
function herdTable(rows){if(!rows.length)return'<div class="empty">Aucun cheptel.</div>';return`<div class="table-wrap"><table><thead><tr><th>Dépt</th><th>EDE</th><th>Éleveur</th><th>Commune</th><th>Mode</th><th>Qualification actuelle</th><th>Vétérinaire</th></tr></thead><tbody>${rows.map(h=>`<tr class="click-row" data-herd="${esc(h.ede)}"><td>${esc(h.dept)}</td><td><strong>${esc(h.ede)}</strong></td><td>${esc(h.name)}</td><td>${esc(h.commune||'')}</td><td>${badgeMode(h.mode)}</td><td>${esc(h.currentQualification||h.qualification||'')}</td><td>${esc(h.vet||'')}</td></tr>`).join('')}</tbody></table></div>`}
function animalTable(rows){if(!rows.length)return'<div class="empty">Aucun animal.</div>';return`<div class="table-wrap"><table><thead><tr><th>Animal</th><th>Travail</th><th>Nom</th><th>EDE</th><th>Sexe</th><th>Naissance</th><th>Présence</th><th>Date sortie</th><th>Cause</th><th>Mère</th></tr></thead><tbody>${rows.map(a=>`<tr class="click-row" data-herd="${esc(a.ede)}"><td>${esc(a.animalId)}</td><td>${esc(a.workNo||'')}</td><td>${esc(a.name||'')}</td><td>${esc(a.ede)}</td><td>${esc(a.sex||'')}</td><td>${fmtDate(a.birthDate)}</td><td>${esc(a.presence||'')}</td><td>${fmtDate(a.exitDate)}</td><td>${esc(a.exitCause||'')}</td><td>${esc(a.motherId||'')}</td></tr>`).join('')}</tbody></table></div>`}
function simpleObjectTable(rows,cols){if(!rows.length)return'<div class="empty">Aucune donnée.</div>';return`<div class="table-wrap"><table><thead><tr>${cols.map(c=>`<th>${esc(c)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${esc(r[c]??'')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function importCard(id,title,help,accept){return`<div class="card"><h2>${title}</h2><p class="help">${help}</p><div class="dropzone" data-drop="${id}"><label for="file_${id}">Choisir le fichier</label><input id="file_${id}" data-import="${id}" type="file" accept="${accept}"><div class="help" style="margin-top:8px">ou glisser-déposer ici</div></div></div>`}
function balance(){const ag=[...analysisAggregate().values()];return{campaign:state.campaign,herds:state.herds.length,guarantee:state.herds.filter(h=>norm(h.mode).includes('garantie')).length,assainissement:state.herds.filter(h=>norm(h.mode).includes('assain')).length,herdsTested:ag.length,animalsTested:ag.reduce((s,x)=>s+x.tested,0),positiveHerds:ag.filter(x=>x.positive>0).length,positiveAnalyses:ag.reduce((s,x)=>s+x.positive,0),toTreat:ag.filter(x=>x.status!=='TRAITÉ').length}}
function balanceHTML(){const b=balance();return`<div class="stat-line"><span class="stat-pill">${b.herds} engagés</span><span class="stat-pill">${b.guarantee} Garantie</span><span class="stat-pill">${b.assainissement} Assainissement</span><span class="stat-pill">${b.herdsTested} dépistés</span><span class="stat-pill">${b.animalsTested} bovins analysés</span><span class="stat-pill">${b.positiveHerds} cheptels positifs</span><span class="stat-pill">${b.positiveAnalyses} positifs</span></div>`}

function bindView(){
  $$('[data-go]').forEach(b=>b.onclick=()=>{state.view=b.dataset.go;render()});
  $$('[data-herd]').forEach(r=>r.onclick=()=>openHerd(r.dataset.herd));
  $$('.analysis-treat').forEach(b=>b.onclick=e=>{e.stopPropagation();openTreatment(b.dataset.ede)});
  if($('#herdQ')) $('#herdQ').oninput=e=>{state.herdFilters.q=e.target.value;$('#app').innerHTML=views.herds();bindView()};
  if($('#herdDept')) $('#herdDept').onchange=e=>{state.herdFilters.dept=e.target.value;render()};
  if($('#herdMode')) $('#herdMode').onchange=e=>{state.herdFilters.mode=e.target.value;render()};
  if($('#animalQ')) $('#animalQ').oninput=e=>{const q=norm(e.target.value);const rows=state.animals.filter(a=>norm([a.animalId,a.workNo,a.name,a.ede].join(' ')).includes(q)).slice(0,500);$('#animalResults').innerHTML=animalTable(rows);$$('[data-herd]',$('#animalResults')).forEach(r=>r.onclick=()=>openHerd(r.dataset.herd))};
  $$('[data-import]').forEach(i=>i.onchange=()=>i.files[0]&&handleImport(i.dataset.import,i.files[0]));
  $$('[data-drop]').forEach(z=>{z.ondragover=e=>{e.preventDefault();z.classList.add('drag')};z.ondragleave=()=>z.classList.remove('drag');z.ondrop=e=>{e.preventDefault();z.classList.remove('drag');const f=e.dataTransfer.files[0];if(f)handleImport(z.dataset.drop,f)}});
  $$('.export-btn').forEach(b=>b.onclick=()=>runExport(b.dataset.export));
  if($('#btnImportBundled')) $('#btnImportBundled').onclick=importBundledHistory;
  if($('#btnAddNN')) $('#btnAddNN').onclick=openNNForm;
  if($('#saveCampaign')) $('#saveCampaign').onclick=async()=>{const v=$('#settingCampaign').value.trim();if(!/^\d{4}\/\d{4}$/.test(v))return toast('Format attendu : 2026/2027');state.campaign=v;await setMeta('currentCampaign',v);render();toast('Campagne enregistrée')};
  if($('#saveSupabase')) $('#saveSupabase').onclick=async()=>{await setMeta('supabaseUrl',$('#sbUrl').value.trim().replace(/\/$/,''));await setMeta('supabaseKey',$('#sbKey').value.trim());toast('Paramètres Supabase enregistrés')};
  if($('#pushSupabase')) $('#pushSupabase').onclick=pushSupabase;
  if($('#pullSupabase')) $('#pullSupabase').onclick=pullSupabase;
  if($('#restoreJsonBtn')) $('#restoreJsonBtn').onclick=()=>$('#restoreJsonInput').click();
  if($('#restoreJsonInput')) $('#restoreJsonInput').onchange=e=>restoreBackup(e.target.files[0]);
  if($('#resetDbBtn')) $('#resetDbBtn').onclick=resetDb;
}

function openModal(html){$('#modalBody').innerHTML=html;$('#modal').hidden=false}
function closeModal(){$('#modal').hidden=true;$('#modalBody').innerHTML=''}
$('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal()};
function openHerd(ede){const h=herdByEde(ede)||{ede};const hist=historyFor(ede);const animals=activeAnimals(ede);const nn=state.nonnegatives.filter(x=>String(x.ede)===String(ede));const desc=state.descendants.filter(x=>String(x.ede)===String(ede));const intro=state.introductions.filter(x=>String(x.ede)===String(ede));const ag=analysisAggregate().get(String(ede));openModal(`<h1>${esc(h.name||'Éleveur')}</h1><div class="stat-line"><span class="stat-pill">EDE ${esc(ede)}</span><span class="stat-pill">Dépt ${esc(h.dept||'')}</span>${badgeMode(h.mode)}<span class="stat-pill">${esc(h.currentQualification||'Qualification non renseignée')}</span></div>${ag?`<div class="notice ${ag.positive?'warn':''}">${statusBadge(ag.status)} · ${ag.tested} dépistés · ${ag.positive} positif(s) · dernier prélèvement ${fmtDate(ag.last)}</div>`:''}<div class="section-tabs"><button class="active">Historique</button><button>Animaux (${animals.length})</button><button>Non négatifs (${nn.length})</button><button>Descendants (${desc.length})</button><button>Introductions (${intro.length})</button></div><div class="timeline">${hist.map(c=>`<div class="event"><strong>${esc(c.campaign)}</strong><small>${esc(c.status||c.situation||'')}</small><p>${esc(c.method||c.screeningPlanned||'')}</p><small>${c.tested?`${c.tested} dépistés · ${c.positive||0} positifs`:''}</small></div>`).join('')||'<div class="empty">Pas d’historique.</div>'}</div><div class="card" style="margin-top:14px"><h3>Situation actuelle</h3><div class="form-grid"><div><b>Vétérinaire</b><br>${esc(h.vet||'')}</div><div><b>Protocole</b><br>${esc(h.protocol||'')}</div><div><b>Qualification AGDS</b><br>${esc(h.qualificationAgds||h.currentQualification||'')}</div><div><b>Qualification nationale</b><br>${esc(h.qualificationNational||'')}</div></div></div><div class="card"><h3>Animaux</h3>${animalTable(animals.slice(0,100))}</div><div class="card"><h3>Non négatifs</h3>${simpleObjectTable(nn,['campaign','animalId','result','date','comment'])}</div><div class="card"><h3>Descendants</h3>${simpleObjectTable(desc,['animalId','motherId','birthDate','presence','exitDate','exitCause'])}</div>`);}
function openTreatment(ede){const a=analysisAggregate().get(String(ede));const t=a?.treatment||{};openModal(`<h2>Traitement analyse — ${esc(ede)}</h2><p>${a?.tested||0} dépistés · ${a?.positive||0} positif(s) · dernière MAJ ${fmtDate(a?.lastUpdate)}</p><div class="form-grid"><div class="field"><label>Date de traitement</label><input id="trDate" type="date" value="${esc(t.treatmentDate||today())}"></div><div class="field"><label>Qualification mise à jour ?</label><select id="trQual"><option value="false">Non</option><option value="true" ${t.qualificationUpdated?'selected':''}>Oui</option></select></div><div class="field"><label>Positifs gérés ?</label><select id="trPos"><option value="false">Non</option><option value="true" ${t.positivesManaged?'selected':''}>Oui</option></select></div><div class="field"><label>Commentaire</label><textarea id="trCom">${esc(t.comment||'')}</textarea></div></div><div class="actions"><button class="primary" id="saveTreatment">Enregistrer</button></div>`);$('#saveTreatment').onclick=async()=>{const obj={id:key(ede,state.campaign),ede:String(ede),campaign:state.campaign,treatmentDate:$('#trDate').value,qualificationUpdated:$('#trQual').value==='true',positivesManaged:$('#trPos').value==='true',comment:$('#trCom').value,updatedAt:new Date().toISOString()};await db.put('analysisTreatments',obj);state.analysisTreatments=await db.all('analysisTreatments');closeModal();render();toast('Traitement enregistré')};}
function openNNForm(){openModal(`<h2>Ajouter un non négatif</h2><div class="form-grid"><div class="field"><label>EDE</label><input id="nnEde"></div><div class="field"><label>Animal</label><input id="nnAnimal"></div><div class="field"><label>Campagne</label><input id="nnCamp" value="${esc(state.campaign)}"></div><div class="field"><label>Résultat</label><select id="nnRes"><option>Positif</option><option>Douteux</option><option>Non négatif</option></select></div><div class="field"><label>Date</label><input id="nnDate" type="date" value="${today()}"></div><div class="field"><label>Commentaire</label><textarea id="nnCom"></textarea></div></div><button class="primary" id="saveNN">Enregistrer</button>`);$('#saveNN').onclick=async()=>{const ede=$('#nnEde').value.trim(),animalId=digits($('#nnAnimal').value);if(!ede||!animalId)return toast('EDE et animal obligatoires');const obj={id:key($('#nnCamp').value,ede,animalId,$('#nnDate').value),campaign:$('#nnCamp').value,ede,animalId,result:$('#nnRes').value,date:$('#nnDate').value,comment:$('#nnCom').value};await db.put('nonnegatives',obj);state.nonnegatives=await db.all('nonnegatives');closeModal();render()};}

async function importBundledHistory(){try{toast('Chargement de l’historique fourni…');const r=await fetch('./migration/Suivi_Paratuberculose_32_65_V9_1_final_sans_analyses.xlsx');if(!r.ok)throw new Error('Fichier historique introuvable');const blob=await r.blob();const f=new File([blob],'historique_V9_1.xlsx',{type:blob.type||'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});await importExcel(f);await loadState();render();toast('Historique chargé')}catch(e){console.error(e);toast('Historique : '+e.message)}}
async function handleImport(type,file){try{toast(`Import de ${file.name}…`);if(type==='migration')await importExcel(file);else if(type.startsWith('animals'))await importAnimals(file,type.endsWith('32')?32:65);else await importAnalysis(file,type.endsWith('32')?32:65);await loadState();render();toast('Import terminé')}catch(e){console.error(e);toast('Erreur import : '+e.message)}}
function readFile(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(r.error);r.readAsArrayBuffer(file)})}
function sheetObjects(wb,name){const sh=wb.Sheets[name];if(!sh)return[];return XLSX.utils.sheet_to_json(sh,{defval:'',raw:false,dateNF:'dd/mm/yyyy'})}
function pick(o,...keys){for(const k of keys){const found=Object.keys(o).find(x=>norm(x)===norm(k));if(found!==undefined&&o[found]!==''&&o[found]!=null)return o[found]}return''}
function parseFrenchDate(v){if(!v)return'';if(v instanceof Date)return v.toISOString();const m=String(v).match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);return m?new Date(+m[3],+m[2]-1,+m[1]).toISOString():v}
async function importExcel(file){if(!window.XLSX)throw new Error('Bibliothèque Excel indisponible : connexion internet nécessaire au premier import.');const data=await readFile(file),w=XLSX.read(data,{type:'array',cellDates:true});
  const herds=sheetObjects(w,'CHEPTELS').map((r,i)=>{const ede=digits(pick(r,'N° cheptel','N° EDE','N° cheptel / EDE'));return{id:ede||`herd${i}`,ede,dept:Number(pick(r,'Dépt','Département'))||Number(ede.slice(0,2)),name:pick(r,'Nom','Éleveur'),commune:pick(r,'Commune'),mode:pick(r,'Mode suivi','Mode de suivi'),protocol:pick(r,'Protocole'),vet:pick(r,'Vétérinaire'),currentQualification:pick(r,'Qualification actuelle','Situation garantie','Qualification AGDS'),qualificationAgds:pick(r,'Qualification AGDS'),qualificationNational:pick(r,'Qualification logiciel national'),raw:r}}).filter(x=>x.ede);
  const campaigns=sheetObjects(w,'CAMPAGNES').map((r,i)=>{const ede=digits(pick(r,'N° cheptel','N° EDE'));const camp=pick(r,'Campagne');return{id:key(camp,ede,i),campaign:camp,ede,dept:Number(pick(r,'Dépt')),name:pick(r,'Nom'),mode:pick(r,'Mode suivi'),situation:pick(r,'Situation garantie'),protocol:pick(r,'Protocole'),screeningPlanned:pick(r,'Dépistage prévu'),method:pick(r,'Méthode'),tested:num(pick(r,'Nb dépistés')),negative:num(pick(r,'Nb négatifs')),positive:num(pick(r,'Nb positifs')),status:pick(r,'Qualif / statut campagne'),campaignDate:parseFrenchDate(pick(r,'Date campagne')),comment:pick(r,'Commentaires / source'),raw:r}}).filter(x=>x.ede&&x.campaign);
  const nns=sheetObjects(w,'NON_NEGATIFS').map((r,i)=>{const ede=digits(pick(r,'N° cheptel','N° EDE')),animalId=digits(pick(r,'N° bovin','Animal','Identifiant bovin'));const camp=pick(r,'Campagne');return{id:key(camp,ede,animalId,i),campaign:camp,dept:Number(pick(r,'Dépt')),ede,animalId,result:pick(r,'Résultat'),date:parseFrenchDate(pick(r,'Date','Date résultat')),presence:pick(r,'Présent / sorti','Présence'),exitDate:parseFrenchDate(pick(r,'Date sortie')),exitCause:pick(r,'Cause sortie'),comment:pick(r,'Commentaires','Commentaire'),raw:r}}).filter(x=>x.ede&&x.animalId);
  const desc=sheetObjects(w,'DESCENDANTS').map((r,i)=>{const ede=digits(pick(r,'N° cheptel','N° EDE')),animalId=digits(pick(r,'N° descendant','N° bovin','Animal'));return{id:key(ede,animalId,i),dept:Number(pick(r,'Dépt')),ede,motherId:digits(pick(r,'N° mère positive','N° mère')),animalId,birthDate:parseFrenchDate(pick(r,'Date naissance')),presence:pick(r,'Présent / sorti','Présence'),exitDate:parseFrenchDate(pick(r,'Date sortie')),exitCause:pick(r,'Cause sortie'),comment:pick(r,'Commentaires','Commentaire'),raw:r}}).filter(x=>x.ede&&x.animalId);
  const intro=sheetObjects(w,'INTRODUCTIONS').map((r,i)=>{const ede=digits(pick(r,'N° cheptel','N° EDE')),animalId=digits(pick(r,'N° bovin','Animal'));return{id:key(ede,animalId,i),dept:Number(pick(r,'Dépt')),ede,animalId,entryDate:parseFrenchDate(pick(r,'Date entrée','Date introduction')),origin:pick(r,'Provenance','Cheptel provenance'),control:pick(r,'Contrôle','Analyse'),result:pick(r,'Résultat'),comment:pick(r,'Commentaires','Commentaire'),raw:r}}).filter(x=>x.ede||x.animalId);
  for(const [s,arr] of [['herds',herds],['campaigns',campaigns],['nonnegatives',nns],['descendants',desc],['introductions',intro]]){await db.clear(s);await db.bulkPut(s,arr)}
  const camp=pick(sheetObjects(w,'PARAMETRES')[1]||{},'Valeur')||currentCampaignDefault(); if(/^\d{4}\/\d{4}$/.test(camp))await setMeta('currentCampaign',camp);
}
function parseDelimited(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(!lines.length)return[];const sep=(lines[0].match(/;/g)||[]).length>(lines[0].match(/,/g)||[]).length?';':',';const parseLine=line=>{const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(ch===sep&&!q){out.push(cur);cur=''}else cur+=ch}out.push(cur);return out.map(v=>v.replace(/^="(.*)"$/,'$1').trim())};const headers=parseLine(lines[0]);return lines.slice(1).map(l=>{const a=parseLine(l),o={};headers.forEach((h,i)=>o[h]=a[i]??'');return o})}
async function importAnimals(file,dept){const text=await file.text(),rows=parseDelimited(text);const arr=rows.map((r,i)=>{const animalId=digits(pick(r,'Identifiant bovin'));if(!animalId)return null;const exitDate=parseFrenchDate(pick(r,'Date sortie'));const code=pick(r,'Cause de sortie');const cm={E:'Élevage',B:'Boucherie',M:'Mort',H:'Héritage',C:'Autoconsommation'};return{id:key(dept,animalId),dept,animalId,motherId:digits(pick(r,'Numéro mère')),ede:digits(pick(r,'Exploitation')),birthDate:parseFrenchDate(pick(r,'Date naissance')),exitDate,presence:exitDate?'Sorti':'Présent',exitCause:cm[code]||code,workNo:pick(r,'Numéro travail'),name:pick(r,'Nom'),sex:pick(r,'Sexe'),raw:r}}).filter(Boolean);const old=state.animals.filter(a=>Number(a.dept)!==dept);await db.clear('animals');await db.bulkPut('animals',[...old,...arr])}
async function importAnalysis(file,dept){const text=await file.text(),rows=parseDelimited(text);const arr=rows.map((r,i)=>{if(pick(r,'Code maladie')!=='PTB'||pick(r,"Base de l'analyse")!=='S'||pick(r,"Type d'analyse")!=='I'||pick(r,'Contexte')!=='P')return null;const ede=digits(pick(r,"N° d'exploitation")),sampleDate=parseFrenchDate(pick(r,'Date de prélèvement')),camp=campaignFromDate(sampleDate);if(!ede||!camp)return null;return{id:key(dept,ede,camp,pick(r,"N° incrément du lot d'analyse")||i,pick(r,'Numéro du dossier laboratoire')),dept,ede,campaign:camp,sampleDate,tested:num(pick(r,"Nombre d'analyse ou de prélèvements effectués")),positive:num(pick(r,"Nombre d'analyses positives")),animalsConcerned:num(pick(r,"Nombre d'animaux concernés par l'analyse")),lastUpdate:parseFrenchDate(pick(r,'Date de la dernière mise à jour')),labFile:pick(r,'Numéro du dossier laboratoire'),raw:r}}).filter(Boolean);const keep=state.analysisLots.filter(x=>Number(x.dept)!==dept||!arr.some(n=>n.campaign===x.campaign));await db.clear('analysisLots');await db.bulkPut('analysisLots',[...keep,...arr])}

function runExport(type){let rows=[],headers=[];const herdRows=state.herds.map(h=>({Département:h.dept,EDE:h.ede,Nom:h.name,Commune:h.commune,Mode:h.mode,Qualification:h.currentQualification,Vétérinaire:h.vet}));if(type==='engages'){rows=herdRows;headers=Object.keys(rows[0]||{})}else if(type.startsWith('garantie')||type.startsWith('ass')){const guarantee=type.startsWith('garantie'),dept=type.endsWith('32')?32:type.endsWith('65')?65:null;rows=herdRows.filter((r,i)=>{const h=state.herds[i];return norm(h.mode).includes(guarantee?'garantie':'assain')&&(!dept||Number(h.dept)===dept)});headers=Object.keys(herdRows[0]||{})}else if(type==='bilan'){rows=[balance()];headers=Object.keys(rows[0])}else if(type==='positifs'){rows=[...analysisAggregate().values()].filter(a=>a.positive>0).map(a=>({EDE:a.ede,Nom:herdByEde(a.ede)?.name||'',Dépistés:a.tested,Négatifs:a.negative,Positifs:a.positive,Date:fmtDate(a.last),Statut:a.status}));headers=Object.keys(rows[0]||{EDE:'',Nom:'',Dépistés:'',Négatifs:'',Positifs:'',Date:'',Statut:''})}else if(type==='nonnegpresent'){const ai=animalIndex();rows=state.nonnegatives.filter(n=>(ai.get(String(n.animalId))?.presence||n.presence)==='Présent').map(n=>({...n,animalName:ai.get(String(n.animalId))?.name||''}));headers=['campaign','dept','ede','animalId','animalName','result','date','comment']}else if(type==='descendants'){rows=state.descendants;headers=['dept','ede','motherId','animalId','birthDate','presence','exitDate','exitCause','comment']}else if(type==='introductions'){rows=state.introductions;headers=['dept','ede','animalId','entryDate','origin','control','result','comment']};download(`PTB_${type}_${state.campaign.replace('/','-')}.csv`,toCSV(rows,headers),'text/csv;charset=utf-8')}

async function makeBackup(){const obj={version:APP_VERSION,createdAt:new Date().toISOString(),meta:state.meta};for(const s of STORES.filter(x=>x!=='meta'))obj[s]=await db.all(s);download(`PTB_GDS_backup_${today()}.json`,JSON.stringify(obj,null,2),'application/json')}
async function restoreBackup(file){if(!file)return;const obj=JSON.parse(await file.text());for(const s of STORES.filter(x=>x!=='meta')){await db.clear(s);if(Array.isArray(obj[s]))await db.bulkPut(s,obj[s])}if(obj.meta)for(const [k,v] of Object.entries(obj.meta))await setMeta(k,v);await loadState();render();toast('Sauvegarde restaurée')}
async function resetDb(){if(!confirm('Effacer toutes les données locales de l’application ?'))return;for(const s of STORES)await db.clear(s);await loadState();render()}

async function supabaseRequest(path,opts={}){const url=state.meta.supabaseUrl,keyv=state.meta.supabaseKey;if(!url||!keyv)throw new Error('Supabase non configuré');const r=await fetch(url+'/rest/v1/'+path,{...opts,headers:{apikey:keyv,Authorization:'Bearer '+keyv,'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=minimal',...(opts.headers||{})}});if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json()}
async function pushSupabase(){try{await setMeta('supabaseUrl',$('#sbUrl').value.trim().replace(/\/$/,''));await setMeta('supabaseKey',$('#sbKey').value.trim());const records=[];for(const s of STORES.filter(x=>x!=='meta'))for(const o of await db.all(s))records.push({dataset:s,id:o.id,payload:o,updated_at:new Date().toISOString()});for(let i=0;i<records.length;i+=500)await supabaseRequest('ptb_records?on_conflict=dataset,id',{method:'POST',body:JSON.stringify(records.slice(i,i+500))});for(const [k,v] of Object.entries(state.meta))await supabaseRequest('ptb_records?on_conflict=dataset,id',{method:'POST',body:JSON.stringify([{dataset:'meta',id:k,payload:{id:k,value:v},updated_at:new Date().toISOString()}])});toast('Synchronisation envoyée')}catch(e){console.error(e);toast('Supabase : '+e.message)}}
async function pullSupabase(){try{await setMeta('supabaseUrl',$('#sbUrl').value.trim().replace(/\/$/,''));await setMeta('supabaseKey',$('#sbKey').value.trim());const rows=await supabaseRequest('ptb_records?select=dataset,id,payload',{method:'GET'});for(const s of STORES)await db.clear(s);for(const r of rows){const target=r.dataset==='meta'?'meta':r.dataset;if(STORES.includes(target))await db.put(target,r.payload)}await loadState();render();toast('Données Supabase récupérées')}catch(e){console.error(e);toast('Supabase : '+e.message)}}

async function init(){await db.open();await loadState();populateCampaignSelector();$('#globalCampaign').onchange=async e=>{state.campaign=e.target.value;await setMeta('currentCampaign',state.campaign);render()};$('#btnBackup').onclick=makeBackup;$$('.nav-btn').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render()});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});render()}
init().catch(e=>{$('#app').innerHTML=`<div class="error">Erreur au démarrage : ${esc(e.message)}</div>`;console.error(e)});
